name: marble
description: "With this app, users can quickly find real estate for rent and purchase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  go_router:
  google_fonts:
  flutter_svg:
  flutter_native_splash:
  flutter_launcher_icons: ^0.13.1
  cached_network_image:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

flutter_native_splash:
  image: assets/images/logo.png
  color: "#232220"
  image_dark: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#232220"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#232220"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans_7pt-Black.ttf
          weight: 900
        - asset: assets/fonts/NunitoSans/NunitoSans_7pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NunitoSans/NunitoSans_7pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans/NunitoSans_7pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans/NunitoSans_7pt-Bold.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans/NunitoSans_7pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans/NunitoSans_7pt-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans/NunitoSans_7pt-ExtraLight.ttf
          weight: 200
